#!/bin/bash

# ATM11 Server Installer for Linux + Crafty Controller
# Downloads latest ATM11 ServerFiles and sets up Minecraft server

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="${SERVER_DIR:-.}"
DOWNLOAD_URL="https://www.curseforge.com/minecraft/modpacks/all-the-mods-11/files"
TEMP_DIR=$(mktemp -d)

echo "=== ATM11 Server Installer ==="
echo "Target directory: $SERVER_DIR"
echo ""

# Cleanup on exit
cleanup() {
    rm -rf "$TEMP_DIR"
}
trap cleanup EXIT

# Check prerequisites
command -v curl >/dev/null 2>&1 || { echo "curl is required but not installed."; exit 1; }
command -v unzip >/dev/null 2>&1 || { echo "unzip is required but not installed."; exit 1; }

# Create server directory if it doesn't exist
mkdir -p "$SERVER_DIR"

echo "Fetching latest ATM11 ServerFiles URL..."
# Get the latest ServerFiles download link from CurseForge
# Note: This uses a simplified approach - you may need to adjust based on CurseForge API changes
LATEST_FILE=$(curl -s "https://www.curseforge.com/minecraft/modpacks/all-the-mods-11/files" | \
    grep -oP 'ServerFiles-\d+\.\d+\.\d+\.zip' | head -1)

if [ -z "$LATEST_FILE" ]; then
    echo "Error: Could not find latest ServerFiles. Please check CurseForge manually."
    exit 1
fi

echo "Found: $LATEST_FILE"
DOWNLOAD_LINK="https://www.curseforge.com/minecraft/modpacks/all-the-mods-11/download/$LATEST_FILE"

# Download ServerFiles
echo "Downloading $LATEST_FILE..."
curl -L "$DOWNLOAD_LINK" -o "$TEMP_DIR/$LATEST_FILE" --progress-bar

# Backup old files
if [ -d "$SERVER_DIR/mods" ] || [ -d "$SERVER_DIR/config" ]; then
    BACKUP_DIR="$SERVER_DIR/backup-$(date +%s)"
    echo "Backing up old files to $BACKUP_DIR..."
    mkdir -p "$BACKUP_DIR"
    [ -d "$SERVER_DIR/mods" ] && mv "$SERVER_DIR/mods" "$BACKUP_DIR/"
    [ -d "$SERVER_DIR/config" ] && mv "$SERVER_DIR/config" "$BACKUP_DIR/"
fi

# Extract new files
echo "Extracting server files..."
unzip -q "$TEMP_DIR/$LATEST_FILE" -d "$SERVER_DIR"

# Set up server.properties if it doesn't exist
if [ ! -f "$SERVER_DIR/server.properties" ]; then
    echo "Creating default server.properties..."
    cat > "$SERVER_DIR/server.properties" << 'EOF'
#Minecraft server properties
#Generated by ATM11 installer
server-port=25565
max-players=20
difficulty=2
gamemode=0
enable-command-block=false
spawn-protection=16
view-distance=10
enable-rcon=false
EOF
fi

# Create startup script
echo "Creating startup script..."
cat > "$SERVER_DIR/start.sh" << 'EOF'
#!/bin/bash
cd "$(dirname "$0")"

# ATM11 Server Startup Script
# Adjust JVM args as needed for your system
JVM_ARGS="-Xmx6G -Xms6G -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

java $JVM_ARGS @user_jvm_args.txt @libraries/net/neoforged/neoforge/1.21.1-52.0.0.26/unix_args.txt nogui
EOF

chmod +x "$SERVER_DIR/start.sh"

# Create eula.txt (auto-accept)
echo "eula=true" > "$SERVER_DIR/eula.txt"

# Store version for update checking
VERSION=$(echo "$LATEST_FILE" | grep -oP 'ServerFiles-\K[\d.]+(?=\.zip)' || echo "unknown")
echo "$VERSION" > "$SERVER_DIR/version.txt"

echo ""
echo "=== Installation Complete ==="
echo "Server installed to: $SERVER_DIR"
echo ""
echo "Next steps:"
echo "1. Review server.properties and customize settings"
echo "2. If using Crafty Controller, add this directory as a new server"
echo "3. To start: $SERVER_DIR/start.sh"
echo ""
